version: 0.2

phases:
  pre_build:
    commands:
      echo trying to list all filess
      - ls
      echo a list of files shows up?
      - cd theSimsFrontend && yarn install
  build:
    commands:
      - cd theSimsFrontend &&yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build