version: 0.2

phases:
  pre_build:
    commands:
      - echo trying to list all filess
      - ls
      - echo now go in one layer?
      - cd ./theSimsFrontend
      - echo gonna list file again after cd
      - ls
      - yarn install --force
  build:
    commands:
      - echo starting the next phrase now ! before yarn build
      - cd ./theSimsFrontend && yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build