version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - cd theSimsFrontend
      - yarn run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build