version: 0.2

phases:
  build:
    commands:
      - echo trying to list all filess
      - ls
      - echo now go in one layer?
      - cd ./theSimsServer
      - echo gonna list file again after cd
      - ls
      - mvn clean package
      - ls
  post_build:
    commands:
      - ls

artifacts:
  files:
    - target/testjpa-1.0.0-RELEASE.jar
